#!/bin/sh
update-rc.d N00-display-controller defaults
#grep -q -F 'i2c-dev' /etc/modules || echo 'i2c-dev' >> /etc/modules
#grep -q -F 'i2c-bcm2708' /etc/modules || echo 'i2c-bcm2708' >> /etc/modules
#sed -i 's/i2c_arm=on/i2c_arm=on,i2c_arm_baudrate=30000/' /boot/config.txt



